name: al_qamar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  hijri: ^3.0.0
  intl: ^0.18.1
  jhijri_picker: ^1.0.1
  table_calendar: ^3.0.9
  widget_mask: ^1.0.0+0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: iranyekanmed
      fonts:
        - asset: assets/fonts/IRANYekanBold.ttf
          weight: 900
        - asset: assets/fonts/IRANYekanMedium.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanRegular.ttf
          weight: 400