name: al_qamar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  widget_mask: ^1.0.0+0
  get_it: ^7.6.4
  hijri: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  syncfusion_flutter_datepicker: ^23.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: iranyekanmed
      fonts:
        - asset: assets/fonts/IRANYekanBold.ttf
          weight: 900
        - asset: assets/fonts/IRANYekanMedium.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanRegular.ttf
          weight: 400