name: al_qamar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  widget_mask: ^1.0.0+0
  get_it: ^7.6.4
  hijri: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  syncfusion_flutter_datepicker: ^23.1.36
  smooth_page_indicator: ^1.1.0
  just_audio: ^0.9.35
  video_player: ^2.7.2
  syncfusion_flutter_pdfviewer: ^23.1.39
  cached_network_image: ^3.3.0
  lottie: ^2.6.0
  just_audio_background: ^0.0.1-beta.10
  flutter_secure_storage: ^9.0.0
  webview_flutter: ^4.4.1
  html: ^0.15.4
  flutter_widget_from_html: ^0.14.5
  share_plus: ^7.2.1
  rxdart: ^0.27.7
  flutter_svg: ^2.0.9
  youtube_player_iframe: ^4.0.4
  marqueer: ^1.4.3
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  open_settings_plus: ^0.1.0
  grouped_list: ^5.1.2
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  device_preview: ^1.1.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/video/
    - android/app/src/main/kotlin/com/example/al_qamar/MainActivity.kt
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/res/mipmap-anydpi-v26/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/example/
    - android/app/src/main/kotlin/com/example/al_qamar/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/.idea/
    - android/gradle/
    - android/gradle/wrapper/
    - android/.gradle/
    - android/.gradle/7.5/
    - android/.gradle/7.5/checksums/
    - android/.gradle/7.5/fileHashes/
    - android/.gradle/7.5/fileChanges/
    - android/.gradle/7.5/vcsMetadata/
    - android/.gradle/7.5/executionHistory/
    - android/.gradle/7.5/dependencies-accessors/
    - android/.gradle/vcs-1/
    - android/.gradle/buildOutputCleanup/

  fonts:
    - family: iranyekanmed
      fonts:
        - asset: assets/fonts/IRANYekanBold.ttf
          weight: 900
        - asset: assets/fonts/IRANYekanMedium.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanRegular.ttf
          weight: 400